name: amadeus-test

services:
  management-db:
    image: postgres:16-alpine
    container_name: management-db
    networks:
      - amadeus-test-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  management-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: management-api
    networks:
      - amadeus-test-net
    depends_on:
      management-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://management-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pgdata:

networks:
  amadeus-test-net:
    name: amadeus-test
